kode = str(input("Masukkan kode karyawan	: "))
nama = str(input("Masukkan nama karyawan	: "))
golongan = str(input("Masukkan golongan	: "))
status = str(input("Masukkan status(1=menikah, 2=blm): "))
if(status == "1"):
    jumlah_anak = int(input("Masukkan jumlah anak : "))

print("====================================")
print("STRUK RINCIAN GAJI KARYAWAN")
print("-----------------------------------------------------------")
print("Nama Karyawan		: ", nama , "(Kode: ", kode, ")")
print("Golongan			: ", golongan)
print("Status menikah   : ", status)
if(status == "1"):
    print("Jumlah anak   : ", jumlah_anak)
print("-----------------------------------------------------------")
if(golongan == "A"):
    gaji_pokok = float(10000000)
    potongan = float(2.5)
    tunjangan_istri = float((10 / 100) * gaji_pokok)
    tunjangan_anak = float((5 / 100) * gaji_pokok * jumlah_anak)
    gaji_kotor = float(gaji_pokok + tunjangan_istri + tunjangan_anak)
    besar_potongan = float(gaji_pokok * (potongan / 100)) 
    gaji_bersih = float(gaji_kotor - besar_potongan)
elif(golongan == "B"):
    gaji_pokok = float(10000000)
    potongan = float(2.0)
    tunjangan_istri = float((10 / 100) * gaji_pokok)
    tunjangan_anak = float((5 / 100) * gaji_pokok * jumlah_anak)
    gaji_kotor = float(gaji_pokok + tunjangan_istri + tunjangan_anak)
    besar_potongan = float(gaji_pokok * (potongan / 100)) 
    gaji_bersih = float(gaji_kotor - besar_potongan)
elif(golongan == "C"):
    gaji_pokok = float(10000000)
    potongan = float(1.5)
    tunjangan_istri = float((10 / 100) * gaji_pokok)
    tunjangan_anak = float((5 / 100) * gaji_pokok * jumlah_anak)
    gaji_kotor = float(gaji_pokok + tunjangan_istri + tunjangan_anak)
    besar_potongan = float(gaji_pokok * (potongan / 100)) 
    gaji_bersih = float(gaji_kotor - besar_potongan)
elif(golongan == "D"):
    gaji_pokok = float(10000000)
    potongan = float(1.0)
    tunjangan_istri = float((10 / 100) * gaji_pokok)
    tunjangan_anak = float((5 / 100) * gaji_pokok * jumlah_anak)
    gaji_kotor = float(gaji_pokok + tunjangan_istri + tunjangan_anak)
    besar_potongan = float(gaji_pokok * (potongan / 100)) 
    gaji_bersih = float(gaji_kotor - besar_potongan)
else:
    print("Maaf input yang anda masukkan salah")
print("Gaji Pokok			: Rp ", gaji_pokok)
if(status == "1"):
    print("Tunjangan Istri/suami  : Rp ", tunjangan_istri)
    print("Tunjangan anak  : Rp ", tunjangan_anak)
print("----------------------------------------------------------- +")
if(status == "1"):
    print("Gaji kotor  : Rp ", gaji_kotor)
print("Potongan (", potongan ,"%)		: Rp ", besar_potongan)
print("----------------------------------------------------------- -")
print("Gaji Bersih			: Rp ", gaji_bersih)
